# Generated by Django 6.1.1 on 2026-09-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Ciudad o Comuna')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del atractivo')),
                ('descripcion_corta', models.CharField(max_length=255, verbose_name='Descripción corta')),
                ('descripcion_larga', models.TextField(verbose_name='Descripción detallada')),
                ('horario', models.CharField(max_length=150, verbose_name='Horario')),
                ('precio', models.CharField(max_length=150, verbose_name='Precio')),
                ('como_llegar', models.TextField(verbose_name='Cómo llegar')),
                ('recomendaciones', models.TextField(verbose_name='Recomendaciones')),
                ('destacado', models.BooleanField(default=False, verbose_name='¿Es destacado?')),
                ('imagen', models.CharField(max_length=255, verbose_name='Ruta de imagen')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('lon', models.FloatField(verbose_name='Longitud')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='lugares_turisticos.categoria', verbose_name='Categoría')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='lugares_turisticos.ciudad', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Lugar Turístico',
                'verbose_name_plural': 'Lugares Turísticos',
            },
        ),
    ]
