# Generated by Django 6.1.1 on 2026-09-23 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del plato')),
                ('descripcion_corta', models.CharField(max_length=255, verbose_name='Descripción corta')),
                ('descripcion_larga', models.TextField(verbose_name='Descripción detallada')),
                ('tiempo_preparacion', models.CharField(max_length=50, verbose_name='Tiempo de preparación')),
                ('dificultad', models.CharField(max_length=50, verbose_name='Dificultad')),
                ('porciones', models.PositiveIntegerField(default=1, verbose_name='Porciones')),
                ('maridaje', models.CharField(blank=True, max_length=255, null=True, verbose_name='Maridaje sugerido')),
                ('destacado', models.BooleanField(default=False, verbose_name='¿Es destacado?')),
                ('imagen', models.CharField(max_length=255, verbose_name='Ruta de imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='gastronomia.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
            },
        ),
        migrations.CreateModel(
            name='PasoPreparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(verbose_name='Número de paso')),
                ('texto', models.TextField(verbose_name='Instrucción del paso')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='gastronomia.plato', verbose_name='Plato')),
            ],
            options={
                'verbose_name': 'Paso de preparación',
                'verbose_name_plural': 'Pasos de preparación',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Ingrediente')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='gastronomia.plato', verbose_name='Plato')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
    ]
